[package]
name = "fontster"
version = "0.1.0"
authors = ["gennyble <gen@nyble.dev>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
fontdue = { git = "https://github.com/mooman219/fontdue" }
